[package]
name = "tfhe-pattern"
version = "0.1.0"
edition = "2024"

[dependencies]
tfhe = { path = "../tfhe-rs/tfhe", features = ["boolean", "shortint", "x86_64-unix"] }
refined-tfhe-lhe  = { path = "../refined-tfhe-lhe"}
rand = { version = "*" }
aligned-vec = { version = "0.5.0" }
rayon = { version = "*"}
lazy_static = "1.4"
clap = { version = "4", features = ["derive"] }